libs = libcrails-router%lib{crails-router}
import intf_libs += libcrails%lib{crails}

lib{crails-action}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

lib{crails-action}:
{
  cxx.export.poptions = "-I$out_root/libcrails-action" "-I$src_root/libcrails-action"
  cxx.export.libs = $intf_libs
}

liba{crails-action}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-action}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-action}: bin.lib.version = "-$version.project_id"
else
  lib{crails-action}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
